DROP TABLE IF EXISTS salary_and_bonuses_taxation CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS salary_and_bonuses CASCADE;
DROP TABLE IF EXISTS taxation CASCADE;
DROP TABLE IF EXISTS positions CASCADE;